name: Deploy Tempest Backend

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Silenda
        uses: actions/checkout@v2
        with:
          repository: yewlabs/silenda
          token: ${{ secrets.GH_PAT }}
          submodules: true

      - name: Checkout Data
        uses: actions/checkout@v2
        with:
          path: '2021-hunt'

      - name: Checkout Dependency
        uses: actions/checkout@v2
        with:
          repository: yewlabs/baba-is-auto
          path: 'libs/baba-is-auto'
          token: ${{ secrets.GH_PAT }}
          submodules: 'recursive'

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect Puzzle Files
        run: python3 deploy_static.py
        shell: bash
        working-directory: 2021-hunt

      - name: Collect Static Files
        run: python3 manage.py collectstatic --noinput
        shell: bash

      - name: Delete old puzzle files.
        run: rm -rf 2021-hunt/static/puzzle_files/
        shell: bash

      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATIONS_CREDENTIAL }}

      - name: Deploy Static
        run: gsutil -m rsync -R static/ gs://silenda-dev/static

      - name: Tar Files
        run: |
          mkdir sflex
          tar hc --exclude='__pycache__' --exclude='sflex' . | tar x -C sflex

      - name: Deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          deliverables: sflex/app-tempest.yaml
          promote: false
